<!-- Website header including logo, nav and email -->
<header>
    <img src="images/pixelprotectors_logodrk.svg" alt="pixel protectors logo header" title="Pixel Protectors logo">
    <nav>
         <a href="index.php">Home</a> 
         <a href="jobs.php">Jobs</a> 
         <a href="apply.php">Applications</a> 
         <a href="about.php">About Us</a>
    </nav>
    <a href="mailto:info@pixelprotectors.com.au" class="button">Contact Us</a>
</header>