<!-- Footer content containing page links, logo and JIRA project link -->
<footer>
    <img src="images/pixelprotectors_logolight.svg" alt="pixel protectors logo footer" title="Pixel Protectors logo">
    <p>
         <a href="index.html">Home</a><br>
         <a href="jobs.html">Jobs</a><br> 
         <a href="apply.html">Applications</a><br> 
         <a href="about.html">About Us</a>
    </p>   
    <p>
         <a href="https://mvewebassignment.atlassian.net/jira/software/projects/MP1/boards/34?atlOrigin=eyJpIjoiOTY4NjM2ZTkwYzkzNDc5Njg0YWRjZGViZDQyNTNkYjIiLCJwIjoiaiJ9" target="_blank">JIRA Project Management</a><br>
         <a href="https://github.com/greenTeaFrappe/MVE_WTP" target="_blank">GitHub Repository</a>
    </p>
</footer>