<!-- Website header including logo, nav and email -->
<header>
    <img src="images/pixelprotectors_logodrk.svg" alt="pixel protectors logo header" title="Pixel Protectors logo">
    <nav>
         <a href="index.html">Home</a> 
         <a href="jobs.html">Jobs</a> 
         <a href="apply.html">Applications</a> 
         <a href="about.html">About Us</a>
    </nav>
    <a href="mailto:info@pixelprotectors.com.au" class="button">Contact Us</a>
</header>